### ISSUE TITLE
Publishing codelist issue

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/opencodelists#396]
I just tried t publish the following codelist https://codelists.opensafely.org/codelist/user/brian-mackenna/low-molecular-weight-heparins/3088164f/

I can't recreate but to briefly describe
-  When I first selected publish it appeared to work on my user profile
- The list was not brought to main OpenCodelists page
- I did a hard refresh and still no codelist
-  I returned to my codelist in the profile and the option to publis was still there
- I hit publish again but it generated a server 500 error
- Going back to my profile the codelist is still there https://codelists.opensafely.org/codelist/user/brian-mackenna/low-molecular-weight-heparins/3088164f/ but option to publish has disappeared
- stillnot on main OpenCodelists page

**Comment by inglesp** [comment]
We wouldn't expect this codelist to appear on the main OpenCodelists page, because we're deliberately only showing codelists that belong to the OpenSAFELY organisation at the moment, and this codelist belongs to Brian.  (I can move it if you like -- let me know.)

I've found the 500 in the logs, and will fix up now.
